### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by XXiaoY** [ATP-1010/FederatedLLM#5]
![ctf498v6rtp8g6s8ar60](https://github.com/user-attachments/assets/845c20f9-b514-4373-b65d-490ae576019b)
nohup python main.py --global_model 'models/TinyLlama-1.1B' --data_path  "./data_wiz" --output_dir './FloRA-heter1-wiz-heter/' --num_communication_rounds 2 --local_num_epochs 1 --stacking True --heter True >> heter1.log 2>&1 

When I run this command, there is an error about loading the model state dictionary, and I don't know how to modify it.

**Comment by Baymacf** [comment]
@XXiaoY Hi, I'm getting the same reported error, how did you fix it?
